name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2
      
    - name: Set Up C++ Environment
      uses: actions/setup-cpp@v2
      with:
        compiler: 'gcc'
        
    - name: Build Project
      run: make
      
    - name: Run Tests
      run: make test
